server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/subscription_db
    username: root
    password: Root123$

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true